In [1]:
from quartopy import play_games, BotAI, Board

In [2]:
%load_ext autoreload
import sys
from pathlib import Path

sys.path.append(r"C:/Users/Laboratorio IA/Desktop/githubs/hierarchical-SAE/")



In [3]:
from bot.CNN_bot import Quarto_bot
from models.CNN1 import QuartoCNN


policy_net = QuartoCNN()

number_of_matches: int = 1
p1 = Quarto_bot(model=policy_net, deterministic=False)
p2 = Quarto_bot(model=policy_net, deterministic=True)  # self play

results, win_rate = play_games(
    matches=number_of_matches,
    player1=p1,
    player2=p2,
    delay=0,
    # verbose=False,
    verbose=True,
    PROGRESS_MESSAGE="Testing bots...",
    save_match=False,
    mode_2x2=True,
)
win_rate

Testing bots...:   0%|          | 0/1 [00:00<?, ?it/s]


(Player 1) [CNN_bot|QuartoCNN1] SELECCIONAR PIEZA
    0      1      2      3      4      5      6      7
  ╔══════╦══════╦══════╦══════╦══════╦══════╦══════╦══════╗
0 ║ LKRN ║ LKRH ║ LKQN ║ LKQH ║ LWRN ║ LWRH ║ LWQN ║ LWQH ║
  ╠══════╬══════╬══════╬══════╬══════╬══════╬══════╬══════╣
1 ║ TKRN ║ TKRH ║ TKQN ║ TKQH ║      ║ TWRH ║ TWQN ║ TWQH ║
  ╚══════╩══════╩══════╩══════╩══════╩══════╩══════╩══════╝

(Player 2) [CNN_bot|QuartoCNN1] COLOCAR PIEZA
    0      1      2      3
  ╔══════╦══════╦══════╦══════╗
0 ║      ║      ║      ║ TWRN ║
  ╠══════╬══════╬══════╬══════╣
1 ║      ║      ║      ║      ║
  ╠══════╬══════╬══════╬══════╣
2 ║      ║      ║      ║      ║
  ╠══════╬══════╬══════╬══════╣
3 ║      ║      ║      ║      ║
  ╚══════╩══════╩══════╩══════╝

(Player 2) [CNN_bot|QuartoCNN1] SELECCIONAR PIEZA
    0      1      2      3      4      5      6      7
  ╔══════╦══════╦══════╦══════╦══════╦══════╦══════╦══════╗
0 ║ LKRN ║ LKRH ║ LKQN ║ LKQH ║ LWRN ║ LWRH ║ LWQN ║ LWQH ║
  ╠═══

defaultdict(<function quartopy.game.play.play_games.<locals>.<lambda>()>,
            {'Player 2': 1})

In [4]:
results[0].keys()

dict_keys(['move_history', 'Player 1', 'Player 2', 'result'])

In [5]:
results[0]["result"]

'Player 2'

In [6]:
results[0]["move_history"]

[{'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'selected',
  'piece': 'TALL, WHITE, CIRCLE, WITHOUT_HOLE',
  'piece_index': 12,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'placed',
  'position': (0, 3),
  'position_index': 3,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000'},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'selected',
  'piece': 'TALL, BLACK, SQUARE, WITH_HOLE',
  'piece_index': 11,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'placed',
  'position': (2, 3),
  'position_index': 11,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000

In [7]:
results[0]["move_history"]

[{'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'selected',
  'piece': 'TALL, WHITE, CIRCLE, WITHOUT_HOLE',
  'piece_index': 12,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'placed',
  'position': (0, 3),
  'position_index': 3,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000'},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'selected',
  'piece': 'TALL, BLACK, SQUARE, WITH_HOLE',
  'piece_index': 11,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'placed',
  'position': (2, 3),
  'position_index': 11,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000

In [8]:
results[0]["Player 1"]

'CNN_bot|QuartoCNN1'

In [9]:
m_h = results[0]["move_history"]
m_h

[{'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'selected',
  'piece': 'TALL, WHITE, CIRCLE, WITHOUT_HOLE',
  'piece_index': 12,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'placed',
  'position': (0, 3),
  'position_index': 3,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000'},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 2',
  'action': 'selected',
  'piece': 'TALL, BLACK, SQUARE, WITH_HOLE',
  'piece_index': 11,
  'attempt': 1},
 {'player_name': 'CNN_bot|QuartoCNN1',
  'player_pos': 'Player 1',
  'action': 'placed',
  'position': (2, 3),
  'position_index': 11,
  'attempt': 1,
  'board_after': '0000000000000000000000000000000000000000000000000000

In [10]:
m_h[0]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'TALL, WHITE, CIRCLE, WITHOUT_HOLE',
 'piece_index': 12,
 'attempt': 1}

In [11]:
m_h[1]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 2',
 'action': 'placed',
 'position': (0, 3),
 'position_index': 3,
 'attempt': 1,
 'board_after': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000'}

In [12]:
m_h[2]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 2',
 'action': 'selected',
 'piece': 'TALL, BLACK, SQUARE, WITH_HOLE',
 'piece_index': 11,
 'attempt': 1}

In [13]:
m_h[3]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'placed',
 'position': (2, 3),
 'position_index': 11,
 'attempt': 1,
 'board_after': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000001000000000000000000000000000000000000000000000000000000000000'}

In [14]:
m_h[4]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'LITTLE, WHITE, SQUARE, WITH_HOLE',
 'piece_index': 7,
 'attempt': 1}

In [15]:
from bot.CNN_bot import Quarto_bot
from models.CNN1 import QuartoCNN


policy_net = QuartoCNN()

number_of_matches: int = 1000
p1 = Quarto_bot(model=policy_net, deterministic=False)
p2 = Quarto_bot(model=policy_net, deterministic=True)  # self play

results, win_rate = play_games(
    matches=number_of_matches,
    player1=p1,
    player2=p2,
    delay=0,
    verbose=False,
    PROGRESS_MESSAGE="Testing bots...",
    save_match=False,
    mode_2x2=True,
)
win_rate

Testing bots...:   0%|          | 0/1000 [00:00<?, ?it/s]

defaultdict(<function quartopy.game.play.play_games.<locals>.<lambda>()>,
            {'Player 1': 525, 'Player 2': 473, 'Tie': 2})

In [16]:
# P1
match_data = results[5]
m_h = match_data["move_history"]
print(match_data["result"])
m_h[0]

Player 2


{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'LITTLE, BLACK, CIRCLE, WITH_HOLE',
 'piece_index': 1,
 'attempt': 1}

In [17]:
# P2
match_data = results[2]
m_h = match_data["move_history"]
print(match_data["result"])
m_h[0]

Player 1


{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'TALL, BLACK, SQUARE, WITH_HOLE',
 'piece_index': 11,
 'attempt': 1}

In [18]:
for idx, r in enumerate(results):
    if r["result"] == "Tie":
        print(idx, r["result"])
        break

853 Tie


In [19]:
# Tie
match_data = results[124]
m_h = match_data["move_history"]
print(match_data["result"])
m_h[0]

Player 2


{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'LITTLE, WHITE, SQUARE, WITH_HOLE',
 'piece_index': 7,
 'attempt': 1}

In [20]:
import numpy as np
import pandas as pd


def convert_2_state_action_reward(match_data, REWARD_FUNCTION_TYPE: str = "propagate"):
    """Convert match data to state, action, reward format for RL training.
    Args:
        match_data (dict): Match data from Quartopy.
        REWARD_FUNCTION_TYPE (str): Type of reward function to use. Options are "propagate", "final", "discount".

    Returns:
    * state_boards (list): List of board states.
    * next_state_boards (list): List of next board states.
    * state_piece (list): List of pieces given to the opponent.
    * next_state_piece (list): List of pieces given by the opponent.
    * action_place (list): List of positions to place the piece.
    * action_sel (list): List of pieces to give to the opponent.
    * reward (list): List of rewards.
    * done (list): List of done flags.
    """
    # When ``REWARD_FUNCTION_TYPE`` == "propagate", the reward of the final state is propagated to all previous states.
    # When "final", only the final state has reward, and all previous states have reward 0.
    # When "discount", rewards are discounted over time.
    # The reward of the final state is 1 (P1 win), -1 (P1 lose) or 0 (draw).

    m_h = match_data["move_history"]
    # Actions place and select are combined in only one action, state, reward
    # State is represented in ``state_boards`` and ``state_piece``
    # Action is represented in ``action_place`` and ``action_sel``
    # Assuming SELF PLAY: the bot plays both players
    # Rewards are from perspective of player 1, and are inverted for the turns of the second player
    # NOTE: ``board_next_state`` includes the final board after placing the piece and thus have the same size as ``board_state`` in winning or drawing.
    # NOTE: ``piece_next_state`` not exist when winning, because there is no selected piece for next turn.

    _current_board = "0"  # first state board is empty
    # The state and next_board include empty board, because:
    # Turn 1 of player 1 sees empty board
    # And, at the start of Turn 1 of player 2 it also sees empty board
    board_state = ["0"]  # board before taking action
    board_next_state = ["0"]  # board after taking action

    # pos_index2vector returns all zeros if piece=-1.
    piece_state = [-1]  # piece given by the opponent ni previous turn
    piece_next_state = []  # piece given to the opponent

    # position to put the piece #index from 0 to 15
    # -1 means no piece placed yet
    action_place = [-1]
    action_sel = []  # piece to give to the opponent #index from 0 to 15

    reward = []
    done = []

    for i, move in enumerate(m_h):
        # --- BOARD
        if move["action"] == "selected":
            pass

        elif move["action"] == "placed":
            _next_board = move["board_after"]

            board_state.append(_current_board)
            board_next_state.append(_next_board)
            _current_board = _next_board
        else:
            raise ValueError(f"Unknown action {move['action']}")

        # --- PIECE
        if move["action"] == "selected":
            _current_piece = move["piece_index"]
            piece_next_state.append(_current_piece)

        elif move["action"] == "placed":
            piece_state.append(_current_piece)

        # --- ACTION
        if move["action"] == "selected":
            action_sel.append(move["piece_index"])

        elif move["action"] == "placed":
            action_place.append(move["position_index"])

    assert len(piece_state) == len(piece_next_state) + 1

    action_sel.append(-1)  # no piece selected after the last move
    piece_next_state.append(-1)  # no piece given after the last move

    _num_states = len(piece_state)
    _num_non_terminal_states = _num_states - 1
    # --- REWARD
    match match_data["result"]:
        case "Player 1":
            R = 1
        case "Player 2":
            R = -1
        case "Tie":
            R = 0
        case _:
            raise ValueError(f"Unknown result {match_data['result']}")

    R_2 = -R  # reward from perspective of player 2

    # Apply reward function
    match REWARD_FUNCTION_TYPE:
        case "final":
            reward = [0] * (_num_states)
            reward.append(R)
        case "propagate":
            reward = [R if i % 2 == 0 else R_2 for i in range(_num_states)]
        case "discount":
            gamma = 0.8
            reward = [
                R * (gamma**i) * (-1) ** (i % 2 == 1)
                for i in reversed(range(_num_states))
            ]
        case _:
            raise ValueError(f"Unknown REWARD_FUNCTION_TYPE {REWARD_FUNCTION_TYPE}")

    # ---- DONE
    done = [False] * _num_non_terminal_states
    done.append(True)  # onnly last state is the ending state

    df = pd.DataFrame(
        {
            # but board_state and board_next_state are str
            "board_state": board_state,
            "board_next_state": board_next_state,
            # the rest are int
            "piece_state": piece_state,
            "piece_next_state": piece_next_state,
            "action_place": action_place,
            "action_sel": action_sel,
            "reward": reward,
            "done": done,
        }
    )
    return df

In [21]:
exp = convert_2_state_action_reward(match_data)
exp

board_state  \
0                                                   0   
1                                                   0   
2   0000000000000000000000000000000000000000000000...   
3   0000000000000000000000000000000000000000000000...   
4   0000000000000000000000000000000000000000000000...   
5   0000000000000000001000000000000000000000000000...   
6   0000000000000000001000000000000000000000000000...   
7   0000000000000000001000000000000000000000000000...   
8   0000000000000000001000000000000000000000000000...   
9   0000000000000000001000000000000000000000000000...   
10  0000000000000000001000000000000000000000000000...   
11  0000000000000000001000000000000000000000000000...   
12  0100000000000000001000000000000000000000000000...   
13  0100000000000000001000000000000000000000000000...   
14  0100000000000000001000000000000000000001000000...   
15  0100000000000000001000000000000000000001000000...   

                                     board_next_state  piece_state  \
0                                                   0           -1   
1   0000000000000000000000000000000000000000000000...            7   
2   0000000000000000000000000000000000000000000000...            6   
3   0000000000000000000000000000000000000000000000...           15   
4   0000000000000000001000000000000000000000000000...            1   
5   0000000000000000001000000000000000000000000000...            3   
6   0000000000000000001000000000000000000000000000...            5   
7   0000000000000000001000000000000000000000000000...           10   
8   0000000000000000001000000000000000000000000000...           11   
9   0000000000000000001000000000000000000000000000...           14   
10  0000000000000000001000000000000000000000000000...           13   
11  0100000000000000001000000000000000000000000000...            0   
12  0100000000000000001000000000000000000000000000...           12   
13  0100000000000000001000000000000000000001000000...            2   
14  0100000000000000001000000000000000000001000000...            4   
15  0100000000000000001000000000000000000001000000...            8   

    piece_next_state  action_place  action_sel  reward   done  
0                  7            -1           7      -1  False  
1                  6            11           6       1  False  
2                 15            13          15      -1  False  
3                  1             5           1       1  False  
4                  3             2           3      -1  False  
5                  5            12           5       1  False  
6                 10             8          10      -1  False  
7                 11             4          11       1  False  
8                 14            15          14      -1  False  
9                 13             0          13       1  False  
10                 0             3           0      -1  False  
11                12             1          12       1  False  
12                 2            14           2      -1  False  
13                 4             7           4       1  False  
14                 8            10           8      -1  False  
15                -1             6          -1       1   True

In [22]:
print(exp.dtypes)

board_state         object
board_next_state    object
piece_state          int64
piece_next_state     int64
action_place         int64
action_sel           int64
reward               int64
done                  bool
dtype: object


In [23]:
print(len(board_state))
print(len(board_next_state))
print(len(piece_state))
print(len(piece_next_state))
print(len(action_place))
print(len(action_sel))
print(len(reward))
print(len(done))

NameError: name 'board_state' is not defined

In [ ]:
print("board_state", set(type(x) for x in board_state))
print("board_next_state", set(type(x) for x in board_next_state))
print("piece_state", set(type(x) for x in piece_state))
print("piece_next_state", set(type(x) for x in piece_next_state))
print("action_place", set(type(x) for x in action_place))
print("action_sel", set(type(x) for x in action_sel))
print("reward", set(type(x) for x in reward))
print("done", set(type(x) for x in done))

board_state {<class 'str'>}
board_next_state {<class 'str'>}
piece_state {<class 'numpy.int64'>}
piece_next_state {<class 'numpy.int64'>}
action_place {<class 'numpy.int32'>}
action_sel {<class 'numpy.int64'>}
reward {<class 'float'>}
done {<class 'numpy.bool_'>}


In [ ]:
m_h[0]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'TALL, BLACK, CIRCLE, WITH_HOLE',
 'piece_index': 9,
 'attempt': 1}

In [ ]:
win_rate

defaultdict(<function quartopy.game.play.play_games.<locals>.<lambda>()>,
            {'Player 2': 428, 'Player 1': 571, 'Tie': 1})

In [ ]:
v = action_place
print(len(v))
v

7


array([-1, 13,  2, 11, 14,  9, 10])

In [ ]:
v = action_sel
print(len(v))
v

7


array([ 4,  8, 12,  6, 14, 13, -1], dtype=int64)

In [ ]:
_num_states = 17
R = 1
gamma = 0.8
reward = [R * (gamma**i) * (-1) ** (i % 2 == 1) for i in reversed(range(_num_states))]
reward

[0.028147497671065624,
 -0.03518437208883203,
 0.043980465111040035,
 -0.054975581388800036,
 0.06871947673600004,
 -0.08589934592000005,
 0.10737418240000006,
 -0.13421772800000006,
 0.1677721600000001,
 -0.20971520000000007,
 0.2621440000000001,
 -0.3276800000000001,
 0.4096000000000001,
 -0.5120000000000001,
 0.6400000000000001,
 -0.8,
 1.0]

In [ ]:
m_h[-1]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 2',
 'action': 'placed',
 'position': (0, 3),
 'position_index': 3,
 'attempt': 12,
 'board_after': '0000000001000000000010000000000000100000000000000000000000001000000000000010000000000000000000000001000000000000000000000000000110000000000000000000010000000000000000000000000000000000000000000000000000010000000000000000010001000000000000000000000100000000'}

In [ ]:
m_h[-2]

{'player_name': 'CNN_bot|QuartoCNN1',
 'player_pos': 'Player 1',
 'action': 'selected',
 'piece': 'LITTLE, WHITE, SQUARE, WITHOUT_HOLE',
 'piece_index': 6,
 'attempt': 4}

## Check piece

In [ ]:
print(len(piece_state))
piece_state

7


array([-1,  4,  8, 12,  6, 14, 13], dtype=int64)

In [ ]:
print(len(piece_next_state))
piece_next_state

7


array([ 4,  8, 12,  6, 14, 13, -1], dtype=int64)

## check state_boards

In [ ]:
# check state_boards
def find_ones(board_str):
    return [i for i, char in enumerate(board_str) if char == "1"]


print(len(board_state))
[find_ones(b) for b in board_state]

7


[[],
 [],
 [77],
 [77, 130],
 [77, 130, 203],
 [77, 110, 130, 203],
 [77, 110, 130, 203, 233]]

In [ ]:
print(len(board_next_state))
[find_ones(b) for b in board_next_state]

7


[[],
 [77],
 [77, 130],
 [77, 130, 203],
 [77, 110, 130, 203],
 [77, 110, 130, 203, 233],
 [77, 110, 130, 203, 218, 233]]

In [ ]:
data = {
    "board_state": board_state,
    "board_next_state": board_next_state,
    "piece_state": piece_state,
    "action_place": action_place,
    "action_sel": action_sel,
    "reward": reward,
    "done": done,
    "piece_next_state": piece_next_state,
}

In [ ]:
from tensordict import TensorDict, set_list_to_stack

In [ ]:
import torch

set_list_to_stack(True).set()
tt = TensorDict(data)
tt

TensorDict(
    fields={
        action_place: Tensor(shape=torch.Size([7]), device=cpu, dtype=torch.int32, is_shared=False),
        action_sel: Tensor(shape=torch.Size([7]), device=cpu, dtype=torch.int64, is_shared=False),
        board_next_state: NonTensorStack(
            ['0', '0000000000000000000000000000000000000000000...,
            batch_size=torch.Size([7]),
            device=None),
        board_state: NonTensorStack(
            ['0', '0', '00000000000000000000000000000000000000...,
            batch_size=torch.Size([7]),
            device=None),
        done: Tensor(shape=torch.Size([7]), device=cpu, dtype=torch.bool, is_shared=False),
        piece_next_state: Tensor(shape=torch.Size([7]), device=cpu, dtype=torch.int64, is_shared=False),
        piece_state: Tensor(shape=torch.Size([7]), device=cpu, dtype=torch.int64, is_shared=False),
        reward: Tensor(shape=torch.Size([17]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
   

In [ ]:
tt["action_sel"]

tensor([ 4,  8, 12,  6, 14, 13, -1])

In [ ]:
torch.tensor(action_sel, dtype=torch.int64),

(tensor([ 4,  8, 12,  6, 14, 13, -1]),)

In [30]:
from torch import Tensor

b_str = m_h[1]["board_after"]
x_board = Board.deserialize(b_str)
x_board.shape
x_board = Tensor(x_board)
x_board = x_board.unsqueeze(0)
x_board.shape

torch.Size([1, 16, 4, 4])

In [31]:
piece = m_h[2]["piece_index"]
x_piece = Board.pos_index2vector(piece)
x_piece.shape
x_piece = Tensor(x_piece)
x_piece = x_piece.unsqueeze(0)
x_piece.shape

torch.Size([1, 16])

In [42]:
torch.cat((x_board, x_board)).shape

torch.Size([2, 16, 4, 4])

In [43]:
import torch

a, b = policy_net(torch.cat([x_board, x_board]), torch.cat([x_piece, x_piece]))
a

tensor([[ 0.0527, -0.0120,  0.0165,  0.0441,  0.0537,  0.0722, -0.0360, -0.0217,
         -0.0797, -0.0399, -0.0200,  0.0755,  0.0650,  0.0451, -0.0296, -0.0048],
        [ 0.0527, -0.0120,  0.0165,  0.0441,  0.0537,  0.0722, -0.0360, -0.0217,
         -0.0797, -0.0399, -0.0200,  0.0755,  0.0650,  0.0451, -0.0296, -0.0048]],
       grad_fn=<TanhBackward0>)

In [52]:
a.shape

torch.Size([2, 16])

In [65]:
idx = torch.Tensor([4, 6]).type(torch.int64).unsqueeze(0)
a.gather(1, idx)

tensor([[ 0.0537, -0.0360]], grad_fn=<GatherBackward0>)

In [64]:
idx.unsqueeze(0).shape

torch.Size([1, 2])

In [ ]:
match_data.keys()

dict_keys(['move_history', 'Player 1', 'Player 2', 'result'])

In [ ]:
exp_all = []
n_last_states = 4
for match_data in results:
    exp = convert_2_state_action_reward(match_data)
    if n_last_states < exp.shape[0]:
        exp = exp.iloc[-n_last_states:]
    # elif n_last_states > exp.shape[0]:
    #     logger.warning(
    #         f"n_last_states ({n_last_states}) is greater than the number of states in the match ({exp.shape[0]}). Using all states."
    #     )
    exp_all.append(exp)

In [ ]:
p_all = pd.concat(exp_all, ignore_index=True)

In [ ]:
p_all.shape

(4000, 8)

In [ ]:
print(p_all.dtypes)

board_state         object
board_next_state    object
piece_state          int64
piece_next_state     int64
action_place         int64
action_sel           int64
reward               int64
done                  bool
dtype: object


In [ ]:
ww).shape

SyntaxError: unmatched ')' (2413123355.py, line 1)

In [ ]:
w = np.stack(p_all["board_state"].apply(Board.deserialize))
ww = w
w_next = np.stack(p_all["board_next_state"].apply(Board.deserialize))
# ww_next = w_next.to_numpy()
TensorDict(
    {
        "board_state": torch.tensor(ww, dtype=torch.int8),
        "board_next_state": torch.tensor(w_next, dtype=torch.int8),
    }
)

TensorDict(
    fields={
        board_next_state: Tensor(shape=torch.Size([4000, 16, 4, 4]), device=cpu, dtype=torch.int8, is_shared=False),
        board_state: Tensor(shape=torch.Size([4000, 16, 4, 4]), device=cpu, dtype=torch.int8, is_shared=False)},
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)

In [24]:
from QuartoRL import gen_experience

In [25]:
td = gen_experience(
    p1_bot=p1,
    p2_bot=p2,
    number_of_matches=100,
    REWARD_FUNCTION_TYPE="propagate",
    n_last_states=4,
    verbose=False,
)
td

Generating experience:   0%|          | 0/100 [00:00<?, ?it/s]

TensorDict(
    fields={
        action_place: Tensor(shape=torch.Size([400]), device=cpu, dtype=torch.int8, is_shared=False),
        action_sel: Tensor(shape=torch.Size([400]), device=cpu, dtype=torch.int8, is_shared=False),
        done: Tensor(shape=torch.Size([400]), device=cpu, dtype=torch.bool, is_shared=False),
        next_state_board: Tensor(shape=torch.Size([400, 16, 4, 4]), device=cpu, dtype=torch.float32, is_shared=False),
        next_state_piece: Tensor(shape=torch.Size([400, 16]), device=cpu, dtype=torch.int8, is_shared=False),
        reward: Tensor(shape=torch.Size([400]), device=cpu, dtype=torch.float32, is_shared=False),
        state_board: Tensor(shape=torch.Size([400, 16, 4, 4]), device=cpu, dtype=torch.float32, is_shared=False),
        state_piece: Tensor(shape=torch.Size([400, 16]), device=cpu, dtype=torch.int8, is_shared=False)},
    batch_size=torch.Size([]),
    device=cpu,
    is_shared=False)

In [26]:
td["action_place"]

tensor([14, 15,  7, 10,  3,  6,  2,  1, 12,  8,  4,  0,  0,  7,  1,  6, 13, 12,
         4,  0, 13, 15,  9,  1,  9, 15,  1,  6,  3,  6, 10,  9,  3, 15,  7,  1,
        10,  1,  6,  7, 14,  7,  9,  6,  3,  0,  2,  8,  0,  2, 14,  1,  4,  0,
         3, 15,  9, 15, 10,  1,  0,  6,  3,  9,  4,  8,  2, 10,  7,  3, 13,  2,
         0,  2,  6,  1,  4,  7,  3, 15, 13, 10,  2,  9,  3,  2,  8, 15, 12,  2,
        13,  8,  0,  6, 13,  1,  7,  2,  8,  1,  2,  9, 14,  6,  8, 12,  1,  3,
         6,  1,  8, 10, 15,  0,  7,  3, 13, 14,  2, 15,  8,  2,  9, 15,  7, 14,
         9,  6, 15,  8,  9,  6,  0,  6,  2, 15, 14,  7,  8,  9,  0,  2, 12,  3,
         9, 13, 15,  1,  2,  0, 14,  1,  0, 13,  2,  7, 13,  3,  9,  1,  3,  4,
        13,  0,  0, 13,  3,  1,  1, 14,  9, 10,  9, 15,  7,  1, 15,  9,  7,  8,
        12,  4,  0,  7,  1,  4,  2,  3,  0,  8,  2,  7,  7, 15,  9,  1,  6, 13,
         1, 10,  1,  6,  7,  9,  4, 15, 13, 14, 14,  1,  7, 10, 12, 10,  4, 15,
         9, 13,  1,  2,  1, 13, 10, 15, 

In [27]:
ab = np.stack(p_all["piece_state"].apply(Board.pos_index2vector))
ab.shape

NameError: name 'p_all' is not defined